# Generated by Django 4.0.5 on 2022-06-23 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GCCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_name', models.CharField(max_length=40, null=True, verbose_name='Name of Corporation')),
                ('district', models.CharField(max_length=40, null=True, verbose_name='District')),
                ('region', models.CharField(max_length=40, null=True, verbose_name='Region')),
                ('email_id1', models.EmailField(max_length=40, null=True, verbose_name='Email ID')),
                ('email_id2', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Alternative Email ID')),
                ('mc', models.CharField(max_length=20, null=True, verbose_name='GCC Commissioner Phone Number')),
                ('me', models.CharField(max_length=20, null=True, verbose_name='GCC Engineer Phone Number')),
                ('date_and_time', models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GCC Detail',
                'verbose_name_plural': 'GCC Details',
            },
        ),
    ]
