# Generated by Django 4.0.2 on 2022-07-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0065_alter_agencyprogressmodel_expenditure_and_more'),
        ('Errorreports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetailsNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'Bank Detail Not Filled in',
                'verbose_name_plural': 'Bank Details Not Filled in',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencybankdetails',),
        ),
        migrations.CreateModel(
            name='PanDetailsNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'PAN Detail Not Filled in',
                'verbose_name_plural': 'PAN Details Not Filld in',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.ulbpancard',),
        ),
    ]
