# Generated by Django 4.0.5 on 2022-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0059_remove_agencybankdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='IFSC_code',
            field=models.CharField(max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='account_number',
            field=models.CharField(max_length=90, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='passbookupload',
            field=models.FileField(help_text='Please attach a clear scanned copy front page of the Bank passbook', null=True, upload_to='passbook/', verbose_name='Passbook Front Page Photo'),
        ),
    ]
