# Generated by Django 4.0.5 on 2022-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0061_agencybankdetails_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='district',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='District'),
        ),
    ]
