# Generated by Django 4.0.5 on 2022-06-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0063_agencybankdetails_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry only in Lakhs. <br> Payment made to Contractor', max_digits=5, null=True, verbose_name='Expenditure (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='FundRelease',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry only in Lakhs. <br>Agency has to send a hard copy of the release request along with photos,etc in the prescribed format', max_digits=10, null=True, verbose_name='Fund Release by TUFIDCO (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='valueofworkdone',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Entry only in Lakhs', max_digits=10, null=True, verbose_name='Value of Work done (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='work_awarded_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry only in Lakhs. <br>With Tax. (Add GST, LWF etc on the above basic cost)', max_digits=10, null=True, verbose_name='Work Order Amount'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='work_awarded_amount2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry only in Lakhs. <br>Without Tax (Basic cost/agreed amount, without GST tax etc)', max_digits=10, null=True, verbose_name='Work Order Amount'),
        ),
    ]
