from django.urls import path
from . import views

urlpatterns = [
    path('export_bus', views.bus_export_tobecommenced_xls, name='export_bus'),
    path('export_btroad', views.btroad_export_tobecommenced_xls, name='export_bt'),
    path('export_ccroad', views.btroad_export_tobecommenced_xls, name='export_cc'),
    path('export_ch', views.ch_export_tobecommenced_xls, name='export_ch'),
    path('export_cr', views.cr_export_tobecommenced_xls, name='export_cr'),
    path('export_cl', views.cl_export_tobecommenced_xls, name='export_cl'),
    path('export_kc', views.kc_export_tobecommenced_xls, name='export_kc'),
    path('export_mt', views.mt_export_tobecommenced_xls, name='export_mt'),
    path('export_mbcb', views.mbcb_export_tobecommenced_xls, name='export_mbcb'),
    path('export_pk', views.pk_export_tobecommenced_xls, name='export_pk'),
    path('export_pb', views.pb_export_tobecommenced_xls, name='export_pb'),
    path('export_rw', views.rw_export_tobecommenced_xls, name='export_rw'),
    path('export_swm', views.swm_export_tobecommenced_xls, name='export_swm'),
    path('export_swd', views.swd_export_tobecommenced_xls, name='export_swd'),
    path('export_wb', views.wb_export_tobecommenced_xls, name='export_wb'),
    path('export_in_bt', views.btroad_export_progress_xls, name='export_in_bt'),
    path('DMAexport_in_bt', views.DMAbtroad_export_progress_xls, name='DMAexport_in_bt'),
    path('export_in_wb', views.wb_export_progress_xls, name='export_in_wb'),
    path('export_in_swd', views.swd_export_progress_xls, name='export_in_swd'),
    path('export_in_rw', views.rw_export_progress_xls, name='export_in_rw'),
    path('export_in_pb', views.pb_export_progress_xls, name='export_in_pb'),
    path('export_in_pk', views.pk_export_progress_xls, name='export_in_pk'),
    path('DMAexport_in_pk', views.DMApk_export_progress_xls, name='DMAexport_in_pk'),
    path('export_in_mbcb', views.mbcb_export_progress_xls, name='export_in_mbcb'),
    path('DMAexport_in_mbcb', views.DMAmbcb_export_progress_xls, name='DMAexport_in_mbcb'),
    path('export_in_mt', views.mt_export_progress_xls, name='export_in_mt'),
    path('DMAexport_in_mt', views.DMAmt_export_progress_xls, name='DMAexport_in_mt'),
    path('export_in_kc', views.kc_export_progress_xls, name='export_in_kc'),
    path('DMAexport_in_kc', views.DMAkc_export_progress_xls, name='DMAexport_in_kc'),
    path('export_in_bs', views.bs_export_progress_xls, name='export_in_bs'),
    path('DMAexport_in_bs', views.DMAbs_export_progress_xls, name='DMAexport_in_bs'),
    path('export_in_cc', views.cc_export_progress_xls, name='export_in_cc'),
    path('DMAexport_in_cc', views.DMAcc_export_progress_xls, name='DMAexport_in_cc'),
    path('export_in_cr', views.cr_export_progress_xls, name='export_in_cr'),
    path('DMAexport_in_cr', views.DMAcr_export_progress_xls, name='DMAexport_in_cr'),
    path('export_in_cl', views.cl_export_progress_xls, name='export_in_cl'),
    path('DMAexport_in_cl', views.DMAcl_export_progress_xls, name='DMAexport_in_cl'),
    path('export_in_ch', views.ch_export_progress_xls, name='export_in_ch')
]
