# Generated by Django 4.0.2 on 2022-07-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('Dashboard', '0003_delete_dashboard_delete_dashboardsingara_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KNMTDashboardR2122',
            fields=[
            ],
            options={
                'verbose_name': 'KNMT (2021-2022)',
                'verbose_name_plural': 'KNMT (2021-2022)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.CreateModel(
            name='KNMTDashboardR2223',
            fields=[
            ],
            options={
                'verbose_name': 'KNMT (2022-2023)',
                'verbose_name_plural': 'KNMT (2022-2023)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
