# Generated by Django 4.0.4 on 2022-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_sectorwisereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserequestmodel',
            name='ApprovedProjectCost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Approved Project Cost'),
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='SchemeShare',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scheme Share'),
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='ULBShare',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ULB Share'),
        ),
    ]
