# Generated by Django 4.0.4 on 2022-05-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_releaserequestmodel_approvedprojectcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='ApprovedProjectCost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Approved Project Cost (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='SchemeShare',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scheme Share (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='ULBShare',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ULB Share (in lakhs)'),
        ),
    ]
