# Generated by Django 4.0.4 on 2022-05-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('Accounts', '0009_alter_releaserequestmodel_approvedprojectcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMAinstallmentReport',
            fields=[
            ],
            options={
                'verbose_name': 'DMA Release-I Installment',
                'verbose_name_plural': 'DMA Release-I Installment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
