# Generated by Django 4.0.4 on 2022-05-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('Accounts', '0010_dmainstallmentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTPinstallmentReport',
            fields=[
            ],
            options={
                'verbose_name': 'CTP Release-I Installment',
                'verbose_name_plural': 'CTP Release-I Installment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
