# Generated by Django 4.0.5 on 2022-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_ctpinstallmentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='project',
            field=models.CharField(max_length=100, null=True, verbose_name='P_ID'),
        ),
    ]
