# Generated by Django 4.0.5 on 2022-06-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_releaserequestmodel_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release1Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Release Amount 1'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release2Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Release Amount 2'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release3Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Release Amount 3'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release4Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Release Amount 4'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release5Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Release Amount 5'),
        ),
    ]
