# Generated by Django 4.0.5 on 2022-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_alter_releaserequestmodel_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='Sector',
            field=models.CharField(blank=True, choices=[('Culvert', 'Culvert'), ('Solid Waste Mgt.', 'Solid Waste Mgt.'), ('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Parks', 'Parks'), ('Market', 'Market'), ('Bus Stand', 'Bus Stand'), ('Schools', 'Schools'), ('Lighting System', 'Lighting System'), ('BT Road', 'BT Road'), ('Roads', 'Roads'), ('Retaining wall', 'Retaining wall'), ('Play Field', 'Play Field'), ('Knowledge Centre', 'Knowledge Centre'), ('Water Fountain', 'Water Fountain'), ('Animal Birth Control Centre', 'Animal Birth Control Centre'), ('CC Road', 'CC Road'), ('Metal Beam Crash Barriers', 'Metal Beam Crash Barriers'), ('Name Boards for Streets', 'Name Boards for Streets'), ('Crematorium', 'Crematorium'), ('Path way for  Different Abled person', 'Path way for  Different Abled person'), ('Paver Block', 'Paver Block')], max_length=100, null=True),
        ),
    ]
