# Generated by Django 4.0.5 on 2022-07-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('reports', '0018_delete_progressnotcommenced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULBReleaseLedger',
            fields=[
            ],
            options={
                'verbose_name': 'ULB Release Ledger',
                'verbose_name_plural': 'ULB Release Ledgers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
