# Generated by Django 4.0.6 on 2022-08-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('reports', '0019_ulbreleaseledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULBReleaseLedgerConsolidatedReport',
            fields=[
            ],
            options={
                'verbose_name': 'ULB Release Ledger Consolidated Report',
                'verbose_name_plural': 'Ulb Release Ledger Consolidated Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
